#!/usr/bin/env bash
# automatic update of eix database after emerge --sync
if [[ -e /var/cache/eix/portage.eix ]]; then 
    cp -a /var/cache/eix/portage.eix /var/cache/eix/previous.eix; 
fi
eix-update
if [[ -e /var/cache/eix/previous.eix ]]; then 
    eix-diff; 
fi
